app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api/v1/", include("galery.urls"), name="galery"),
    path("", include("pages.urls"), name="pages"),
    # path('api/', include(('core.routers', 'core'), namespace='core-api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/pages/urls.py
from django.urls import path

from .views import (
    AlbumCreateView,
    AlbumUpdateView,
    AlbumView,
    Home,
    PhotoCreateView,
)

app_name = "pages"

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("album", AlbumCreateView.as_view(), name="album-create"),
    path(
        "album/<slug:slug>/edit", AlbumUpdateView.as_view(), name="album-edit"
    ),
    path("album/<slug:slug>", AlbumView.as_view(), name="album"),
    path(
        "album/<slug:slug>/photo",
        PhotoCreateView.as_view(),
        name="album-add-photo",
    ),
    path("photo", PhotoCreateView.as_view(), name="photo-create"),
]

app/galery/models.py
import json
import random
from typing import Optional

from django.contrib.auth import get_user_model
from django.contrib.gis.db import models as gis_models
from django.db import models
from django.template.defaultfilters import slugify  # new
from django.utils.translation import gettext_lazy as _
from exif import Image
from sorl.thumbnail import ImageField
from taggit.managers import TaggableManager


class Album(models.Model):
    """Album"""

    label = models.CharField(
        max_length=100, verbose_name=("Label"), unique=True
    )
    description = models.TextField(verbose_name=("Description"), default="")
    timestamp_create = models.DateTimeField(auto_now_add=True)
    timestamp_update = models.DateTimeField(auto_now=True)
    slug = models.SlugField(default="", null=False, unique=True)

    def __str__(self):
        return f"{self.label}"

    def save(self, *args, **kwargs):
        if not self.slug or self.slug == "":
            self.slug = slugify(self.label)
            print(self.slug)
        return super().save(*args, **kwargs)


class Tags(models.Model):
    """Image tags"""

    label = models.CharField(max_length=100, verbose_name=("Label"))
    timestamp_create = models.DateTimeField(auto_now_add=True)
    timestamp_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.label}"


class Photo(models.Model):
    """
    A class thaat determines how photos will be saved into the database
    """

    name = models.CharField(max_length=244, verbose_name=_("Name"))
    description = models.TextField(verbose_name=_("Description"))
    city = models.CharField(max_length=244, verbose_name=_("City"), blank=True)
    country = models.CharField(
        max_length=244, verbose_name=_("Country"), blank=True
    )
    geom = gis_models.PointField(
        srid=4326, verbose_name=_("Geometry"), blank=True, null=True
    )
    album = models.ForeignKey(
        Album, on_delete=models.CASCADE, verbose_name=_("Album")
    )
    # tags = models.ManyToManyField(Tags)
    tags = TaggableManager()
    photographer = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        verbose_name=_("Photographer"),
        blank=True,
        null=True,
    )
    exif_data = models.JSONField(
        verbose_name=_("Exif data"), blank=True, null=True
    )
    timestamp_create = models.DateTimeField(auto_now_add=True)
    timestamp_update = models.DateTimeField(auto_now=True)
    image = ImageField(upload_to="photo")
    slug = models.SlugField(default="", null=False)

    def __str__(self):
        """
        String representation
        """
        return f"{self.name}"

    @property
    def exif_dict(self) -> Optional[dict]:
        """Exif data as dict"""
        return json.loads(self.exif_data) if self.exif_data else None

    @property
    def exif_full(self):
        """Get full exif data from image"""
        exif = Image(self.image)
        print(exif.get_all())
        if exif.has_exif:
            data = {exif.get_all()[key] for key in exif.get_all()}
            return data
        return {}

    @classmethod
    def show_all_photos(cls):
        """
        A method to return all photos posted in order of the most
        recent to oldest
        """
        return cls.objects.order_by("timestamp_create")[::-1]

    @classmethod
    def show_random_photo(cls):
        """
        A method which returns a random photo
        """
        all_photos = cls.show_all_photos()
        random_id = random.randint(1, len(all_photos))

        return cls.objects.get(id=random_id)

    @classmethod
    def delete_photo(cls, pk):
        """
        A method to delete an object
        """

        return cls.objects.filter(pk=pk).delete()

    @classmethod
    def get_photo_by_id(cls, pk):
        """
        A method to get a photo based on its id
        """
        return cls.objects.filter(pk=pk)[0]

    @classmethod
    def search_photo_by_category(cls, search):
        """
        A method to return all photos that fall under a certain catergory
        """
        return cls.objects.filter(categories__name__icontains=search)

    @classmethod
    def filter_by_location(cls, pk):
        """
        A method to filter all photos based on the location in which they were
        taken
        """
        return cls.objects.filter(location__id=pk)

    def save(self, *args, **kwargs):
        exif = Image(self.image)
        print(exif.get_all())
        if exif.has_exif:
            data = {
                key: exif.get_all()[key]
                for key in [
                    "lens_model",
                    "lens_make",
                    "artist",
                    "model",
                    "make",
                    "aperture_value",
                    "exposure_bias_value",
                    "focal_length",
                    "focal_length_in_35mm_film",
                    "datetime_original",
                    "photographic_sensitivity",
                    "exposure_time",
                ]
                if key in exif.get_all()
            }
            self.exif_data = json.dumps(data)
        return super().save(*args, **kwargs)

app/pages/templates/album.html
{% extends 'base.html' %}
{% load i18n text_replace thumbnail static %}
{% block content %}
  <div class="container py-5">
    <h2 class="text-center mb-4 fw-bolder">{{ object.label }}</h2>
    <p class="text-center text-muted">{{ object.description }}</p>
    <div class="grid-container">
      {% for photo in object.photo_set.all %}
        <div class="grid-item">
          <a href="#" data-bs-toggle="modal" data-bs-target="#image-{{ photo.pk }}">
            {% thumbnail photo.image '300x300' crop='center' as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ photo.label }}" loading="lazy" />
            {% endthumbnail %}
          </a>
          <div class="image-overlay">
            <h5>{{ photo.name }}</h5>
            <p class="mb-0 text-truncate">{{ photo.description }}</p>
          </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="image-{{ photo.pk }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-xl modal-fullscreen">
            <div class="modal-content">
              <button type="button" class="btn-close close-link" data-bs-dismiss="modal" aria-label="Close"></button>
              <div class="modal-body">
                <div class="row">
                  <div id="imageDisplay" class="col-12 col-md-8 d-flex align-items-center">
                    <img class="p-5 shadow rounded" src="{{ photo.image.url }}" alt="{{ photo.label }}" loading="lazy" />
                  </div>
                  <div id="imageData" class="col-12 col-md-4 mt-5 mt-md-1 pt-1 overflow-auto h-100">
                    <h2 class="pretty-title fw-bolder">{{ photo.name }}</h2>
                    <p class="fw-lighter">by {{ photo.photographer|default_if_none:'-' }}</p>
                    <p class="fw-lighter">
                      {% for tag in photo.tags.all %}
                        <span class="badge text-bg-secondary">{{ tag.name }}</span>
                      {% endfor %}
                    </p>
                    <p>{{ photo.description }}</p>
                    <dl>
                      {% for k, v in photo.exif_dict.items %}
                        <dt>{{ k|underscore_to_space }}</dt>
                        <dd>{{ v }}</dd>
                      {% endfor %}
                    </dl>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
      {% if user.is_authenticated %}
        <div class="grid-item plus-bg">
          <a href="{% url 'pages:album-add-photo' slug=object.slug %}"><img src="{% static 'plus.svg' %}" class="plus-padding" /></a>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

app/pages/templates/base.html
{% load static i18n %}
{% translate 'About' as about_title %}
{% translate 'Contact' as contact_title %}
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors" />
    <meta name="generator" content="Hugo 0.104.2" />
    <title>{{ title }}</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.2/css/bootstrap.min.css" integrity="sha512-CpIKUSyh9QX2+zSdfGP+eWLx23C8Dj9/XmHjZY2uDtfkdLGo0uY12jgcnkX9vXOgYajEKb/jiw67EYm+kBf+6g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'app.css' %}" />
    <meta name="theme-color" content="#712cf9" />
  </head>
  <body class="d-flex flex-column h-100">
    <header>
      <div class="collapse bg-white" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <h4 class="text-black pretty-title">{{ about_title }}</h4>
              <p class="text-muted">{{ owner.introduction }}</p>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-white bg-white shadow-sm">
        <div class="container">
          <a href="/" class="navbar-brand d-flex align-items-center pretty-title">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24">
              <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
              <circle cx="12" cy="13" r="4" />
            </svg>
            <strong>{{ title }}</strong>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        </div>
      </div>
    </header>

    <main class="flex-shrink-0">
      {% block content %}
      {% endblock %}
    </main>

    <footer class="footer mt-auto py-3 bg-light shadow">
      <div class="container d-flex">
        <div class="col-md-6 d-flex align-items-center">
          <span class="text-muted"><a href="https://github.com/hypsug0/PhotoGalery" target="_blank">PhotoGalery</a>, {{ owner.username }}, {% now 'Y' %}</span>
        </div>

        <ul class="nav col-md-6 justify-content-end list-unstyled d-flex">
          {% for social in owner.socials.all %}
            <li class="ms-3">
              <a href="{{ social.url }}" class="text-muted" target="_blank">
                {% with img_static=social.network|add:'.svg' %}
                  <img src="{% static img_static %}" class="bi" width="24" height="24" />
                {% endwith %}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.2/js/bootstrap.min.js" integrity="sha512-5BqtYqlWfJemW5+v+TZUs22uigI8tXeVah5S/1Z6qBLVO7gakAOtkOzUtgq6dsIo5c0NJdmGPs0H9I+2OHUHVQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>
  </body>
</html>

app/pages/templates/form.html
{% extends 'base.html' %}
{% load i18n  crispy_forms_tags %}

{% block content %}
  <div class="album py-5 bg-light">
    <div class="container">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <div class=" text-end">
        <input class="btn btn-success" type="submit" value="{% translate "Save" %}" />
        </div>
      </form>
    </div>
  </div>
{% endblock %}

app/pages/templates/home.html
{% extends 'base.html' %}
{% load i18n thumbnail static %}
{% block content %}
  <section class="py-5 text-center container">
    <div class="row py-lg-3">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">{{title}}</h1>
        <p class="lead text-muted">{{ owner.introduction }}</p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
        <div class="grid-container">
          {% for object in object_list %}
          <a href="{% url 'pages:album' slug=object.slug %}">
            <div class="grid-item">

                {% if   object.photo_set %}
                {% thumbnail  object.photo_set.first.image '300x300' crop='center' as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ object.label }}" loading="lazy" />
                {% endthumbnail %}
                {% else %}
                GO
                {% endif %}

              <div class="image-overlay">
                <h5>{{ object.label }}

                </h5>
                <p class="mb-0 text-truncate">{{ object.description }}</p>
                <small class="text-muted">
                  {% if user.is_authenticated %}
                  <i data-feather="edit"></i>
                  {% endif %}
                  {{object.timestamp_create}}
                </small>
              </div>
            </div>
          </a>
        {% empty %}
          No objects yet.
        {% endfor %}
        {% if user.is_authenticated %}
        <div class="grid-item plus-bg">
          <a href="{% url 'pages:album-create' %}"><img src="{% static 'plus.svg' %}" class="plus-padding " /></a>
        </div>
        {% endif %}
      </div>
  </div>
{% endblock %}